### ISSUE TITLE
Offline Funtionality

### ISSUE THREAD

**Issue by TowelSniffer** [lovac42/JSLoader#3]
With the PGN chess flashcards deck, this addon does not work offline (the board will load but not the pieces). I can get it working offline on my mobile by putting the js files in my media folder.

**Comment by lovac42** [comment]
Were you able to load the images offline when you use JS Booster?

It works on mobile because the images are cached, if you clear the cache you would run into the same issue. Anki, however, clears the cache after each card review.

- You can write an addon to enable caching on Anki, but this raises security issues.
- You can change the JS to use offline images provided that the license allows it. This may take 1-2 weeks of testing and debugging to get it right, but feel free to make a pull request if you get it working.

**Comment by TowelSniffer** [comment]
To answer your first question no I wasn't. But thanks for clarifying for me. Actually rather than rewriting the JS I was thinking it would be easier to redesign the pgn chess card template to use the LT-PGN-VIEWER instead. http://www.lutanho.net/pgn/pgnviewer.html. I will let you know how this goes if I find the time. Also thanks again for being so helpful.
